### ISSUE TITLE
运行demo，发现有几处跟效果图不符，怀疑代码没有上传完毕。

### ISSUE THREAD

**Issue by manuchen** [scsfwgy/WeixinRecord#3]
1，松开结束，没有体现出来
2，松开取消，没有体现出来
3，再次点击语音播放条，没有暂停
4，对设置录音时长，没有暴露友好的方法

感谢你的分享，这个demo对我帮助很大。

**Comment by scsfwgy** [comment]
1. 松开结束有的
2. 是上滑取消
3. 这个是我没注意，没有处理好，晚会加上
4. 这个没有考虑到，我处理一下
* tip:代码是完善的。如果代码不完善你是运行不了的~
* tip:如果发现任何问题可以提问；如果有改动可以PR;一起完善~

**Comment by manuchen** [comment]
额，使用的时候，发现长按录音，无法设置为gone。使用了clearAnimator(),设置动画为null等方法，都不起作用。
对于1,2.我是说长按录音上面的文本，没有显示出来。

**Comment by manuchen** [comment]
你好。长按录音，无法设置为gone。这个我找了网上很多办法，但是还是没有能实现。继续努力，我这几天周末在线等。

**Comment by manuchen** [comment]
一致在行动，但是还是没有解决。我想了个法子，将AudioRecordButton跟button一起放到framelayout里面，然后在完成录音的时候，将buttonshow出来，以便遮盖AudioRecordButton

**Comment by scsfwgy** [comment]
不太明白你的意思啊。是想要把录音这个按钮设置为不可点击或者隐藏对吗？

**Comment by manuchen** [comment]
是的。我就是想再录制音频结束后，将按钮设置为隐藏。刚刚关电脑午休去了，收到邮件之后，立马开的机。在线等。

**Comment by scsfwgy** [comment]
那你看这样行不，直接设置为不可点击。隐藏的话，你得有其它布局覆盖啊。设置为不可点击是可以的。

**Comment by scsfwgy** [comment]
你这个问题，解决方案很多的。你可以考虑把这个按钮放到一个Linnerout中，把这个Linnerout隐藏即可。再说了，这个按钮只是一个普通的控件，本身也是可以隐藏的。。

**Comment by manuchen** [comment]
事实上我都试过。还是行不通的。可能是哪里引用到了。根本隐藏不了。

**Comment by scsfwgy** [comment]
//com.gaoyuan.weixinrecord.example.ExampleActivity，测试可用
       mEmLvRecodeList = (ListView) findViewById(R.id.em_lv_recodeList);
        mEmTvBtn = (AudioRecordButton) findViewById(R.id.em_tv_btn);
        //设置不想要可见或者不想被点击
        // mEmTvBtn.setVisibility(View.GONE);//隐藏
       // mEmTvBtn.setCanRecord(false);//重写该方法，设置为不可点击

**Comment by manuchen** [comment]
你这个是初始化的时候，将其设置为不可见，我调用mEmTvBtn.setVisibility(View.GONE);//隐藏这段代码也能实现。我的应用场景是录完一段音频完毕后设置为不可见。

**Comment by manuchen** [comment]
mEmTvBtn.setAudioFinishRecorderListener(new AudioRecordButton.AudioFinishRecorderListener() {
                            @Override
                            public void onFinished(float seconds, String filePath) {
//                                Record recordModel = new Record();
//                                recordModel.setSecond((int) seconds <= 0 ? 1 : (int) seconds);
//                                recordModel.setPath(filePath);
//                                recordModel.setPlayed(false);
//                                mRecords.add(recordModel);
//                                mExampleAdapter.notifyDataSetChanged();

                                //添加到数据库
//                                mgr.add(recordModel);
//                                mEmTvBtn.clearAnimation();
//                                mEmTvBtn.setAnimation(null);
//                                mEmTvBtn.setVisibility(View.GONE);

**Comment by manuchen** [comment]
看了很多，肯定是哪里的资源一直被mEmTvBtn持有者，导致无法被gone掉。算了，我只能使用别的控件，去实现我的业务逻辑了。

**Comment by scsfwgy** [comment]
只要这一句即可。亲测可以，就是你这个位置。你这真是==。一直不行。
mEmTvBtn.setVisibility(View.GONE);
